version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - store_artifacts:
          path: Fabric/bin/Debug/netstandard2.0/
          destination: lib
      - run: cd Fabric.Tests/ && dotnet xunit -xml test/results.xml
      - store_test_results:
          path: test/results.xml
